### ISSUE TITLE
supervisorctl cannot connect to supervisord

### ISSUE THREAD

**Issue by andrewn** [radiodan-archive/meta-radiodan#2]
```
root@radiodan:~# supervisorctl
http://localhost:9001 refused connection
```

This is because `supervisord` is started with the `-c` flag pointing to:

```
python /usr/bin/supervisord -c /etc/supervisor/supervisor.conf
```

`/etc/supervisor/supervisor.conf` needs to have the following lines added:

```
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
```

(see: http://supervisord.org/configuration.html#rpcinterface-x-section-settings)

You'll then be able to run `supervisorctl -c /etc/supervisor/supervisor.conf` to control the processes.

**Comment by tthef** [comment]
The config is fixed; I also tweaked the packaging so the config is now under /etc/supervisord.conf, and the -c option is no longer needed.
